# Generated by Django 4.0 on 2022-06-02 20:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('raw_file', models.FileField(upload_to='files/issues/')),
                ('cover_image', models.ImageField(upload_to='issue_cover_images')),
                ('name', models.CharField(max_length=128)),
                ('authors', models.TextField(help_text='Authors list comma or new line seperated here')),
                ('subject', models.CharField(max_length=32)),
                ('pages_number', models.IntegerField()),
                ('publishing_date', models.DateField()),
                ('is_issue', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
