# Generated by Django 4.0 on 2022-06-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='views',
            new_name='views_count',
        ),
    ]
