# Generated by Django 4.0 on 2022-06-02 20:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('post_text', models.TextField()),
                ('post_image', models.ImageField(upload_to='blog_post_images')),
                ('contributors', models.TextField(help_text='All contributors comma or new line seperated here')),
                ('subject', models.CharField(max_length=32)),
                ('reading_time', models.IntegerField()),
                ('posting_date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
