# Generated by Django 4.0 on 2022-08-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_views_blogpost_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='posting_date',
            field=models.DateTimeField(),
        ),
    ]
