# Generated by Django 4.0 on 2023-03-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_preview_alter_blogpost_posting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subject',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
